# Generated by Django 4.1 on 2022-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='Nombre')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Nombre')),
                ('telefono', models.IntegerField(blank=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
            ],
        ),
    ]
