# Generated by Django 4.1 on 2022-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=20, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='Usuario'),
        ),
    ]
