# Generated by Django 4.1 on 2022-09-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('1', 'SuperUsuario'), ('2', 'Usuario')], default=2, max_length=1),
        ),
    ]
