# Generated by Django 4.1 on 2022-09-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, verbose_name='Telefono'),
        ),
    ]
