# Generated by Django 4.1 on 2022-09-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, verbose_name='Telefono'),
        ),
    ]
