# Generated by Django 4.1 on 2022-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='Telefono'),
        ),
    ]
