# Generated by Django 4.1 on 2022-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_usuarios_telefono_usuarios_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
