# Generated by Django 4.1 on 2022-09-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Proyecto')),
                ('activo', models.BooleanField(verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(verbose_name='activo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuarios')),
            ],
        ),
    ]
